-- Migration: Create topics table for auto-generated categories
-- Description: Stores auto-generated topic categories from LLM/embedding clustering
-- Part of Task 1.4.2

-- Create table for storing auto-generated topic categories
CREATE TABLE IF NOT EXISTS topics (
    -- Primary identifier
    id SERIAL PRIMARY KEY,

    -- Unique topic identifier (deterministic, used for Qdrant filtering)
    -- Format: topic_{cluster_id} (e.g., "topic_0", "topic_1", "topic_42")
    topic_id VARCHAR(50) UNIQUE NOT NULL,

    -- Hebrew topic name (generated by LLM from cluster analysis)
    name_he VARCHAR(255) NOT NULL,

    -- English topic name (optional, for admin/debugging)
    name_en VARCHAR(255),

    -- Topic description in Hebrew
    description_he TEXT,

    -- Topic description in English (optional)
    description_en TEXT,

    -- Keywords associated with this topic (Hebrew, comma-separated or JSON array)
    keywords_he TEXT[],

    -- Keywords in English (optional)
    keywords_en TEXT[],

    -- Representative law IDs (sample laws that best represent this topic)
    -- Stored as array of law_item_id strings
    representative_law_ids TEXT[],

    -- Centroid embedding (optional, stored as base64 or external reference)
    -- Can be used for topic-based search or for reassigning laws
    centroid_embedding_ref VARCHAR(100),

    -- Number of laws currently assigned to this topic
    law_count INTEGER DEFAULT 0,

    -- Cluster quality score (silhouette score, cohesion metric, etc.)
    cluster_quality_score DECIMAL(5, 4),

    -- Generation metadata
    generation_method VARCHAR(50) DEFAULT 'clustering'
        CHECK (generation_method IN ('clustering', 'manual', 'llm_suggested', 'hybrid')),

    -- Model/algorithm used for clustering
    clustering_algorithm VARCHAR(100),

    -- Model used for name generation
    llm_model VARCHAR(100),

    -- Hierarchy support (for potential nested topics)
    parent_topic_id INTEGER REFERENCES topics(id) ON DELETE SET NULL,
    depth_level INTEGER DEFAULT 0,

    -- Display order for UI
    display_order INTEGER DEFAULT 0,

    -- Whether this topic is active and should be displayed
    is_active BOOLEAN DEFAULT TRUE,

    -- Whether this topic was manually reviewed/approved
    is_reviewed BOOLEAN DEFAULT FALSE,
    reviewed_at TIMESTAMP,
    reviewed_by VARCHAR(255),

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Version for tracking regenerations
    version INTEGER DEFAULT 1
);

-- Indexes for efficient querying

-- Index on topic_id for fast lookups and Qdrant reference matching
CREATE INDEX IF NOT EXISTS idx_topics_topic_id ON topics(topic_id);

-- Index on name_he for search by topic name
CREATE INDEX IF NOT EXISTS idx_topics_name_he ON topics(name_he);

-- Index for active topics (most common query pattern)
CREATE INDEX IF NOT EXISTS idx_topics_active ON topics(is_active) WHERE is_active = TRUE;

-- Index for hierarchical queries
CREATE INDEX IF NOT EXISTS idx_topics_parent ON topics(parent_topic_id);

-- Index for display ordering
CREATE INDEX IF NOT EXISTS idx_topics_display_order ON topics(display_order);

-- Index for law count ordering (popular topics first)
CREATE INDEX IF NOT EXISTS idx_topics_law_count ON topics(law_count DESC);

-- GIN index on Hebrew keywords for array containment queries
CREATE INDEX IF NOT EXISTS idx_topics_keywords_he ON topics USING gin(keywords_he);

-- GIN index on representative law IDs
CREATE INDEX IF NOT EXISTS idx_topics_representative_laws ON topics USING gin(representative_law_ids);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_topics_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_topics_updated_at ON topics;
CREATE TRIGGER trigger_topics_updated_at
    BEFORE UPDATE ON topics
    FOR EACH ROW
    EXECUTE FUNCTION update_topics_updated_at();

-- Comments for documentation
COMMENT ON TABLE topics IS 'Auto-generated topic categories from law clustering for browse/filter functionality';
COMMENT ON COLUMN topics.topic_id IS 'Deterministic ID: topic_{cluster_id} for Qdrant filtering';
COMMENT ON COLUMN topics.name_he IS 'Hebrew topic name generated by LLM from cluster representative laws';
COMMENT ON COLUMN topics.keywords_he IS 'Array of Hebrew keywords associated with this topic';
COMMENT ON COLUMN topics.representative_law_ids IS 'Sample law_item_ids that best represent this topic cluster';
COMMENT ON COLUMN topics.cluster_quality_score IS 'Quality metric (0-1) indicating cluster cohesion';
COMMENT ON COLUMN topics.generation_method IS 'How topic was created: clustering, manual, llm_suggested, hybrid';
COMMENT ON COLUMN topics.parent_topic_id IS 'FK for hierarchical topic structure (optional)';
COMMENT ON COLUMN topics.version IS 'Incremented when topic is regenerated to track changes';
